version: "3.9"

services:
  db:
    image: # name of image
    environment:
      POSTGRES_USER: #postgres user
      POSTGRES_PASSWORD: #password of postgres user
      POSTGRES_DB: #db name
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U name-of-database"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: #db url
      JWT_SECRET: #jwt secret
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: